replicaCount: 4
image:
  repository: aadil77/nagp26-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: gce
  host: employees-api.nagap26.com

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

sql:
  enabled: true
  image: mcr.microsoft.com/mssql/server:2022-latest
  storage:
    size: 10Gi
    storageClass: standard
    maxPool: "100"
    minPool: "0"
  saUser: sa
  # SA password should be provided via sealed secret or external secrets in production
  saPassword: "REPLACE_ME"
  dbName: "NAGP26_DB"
  init:
    enabled: true
  backup:
    enabled: false
    schedule: "0 2 * * *"
    image: myorg/mssql-backup:latest
    gcsBucket: my-backups-bucket

initJob:
  enabled: true

hpa:
  enabled: true
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
