apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp26-app
  namespace: nagp26
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nagp26-app
  template:
    metadata:
      labels:
        app: nagp26-app
    spec:
      containers:
        - name: nagp26-app
          image: aadil77/nagp26-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: DB_SERVER
              value: "nagp26-sql"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sql-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-credentials
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nagp26-app
  namespace: nagp26
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: nagp26-app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nagp26-app-hpa
  namespace: nagp26
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nagp26-app
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50