apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nagp26-app
  namespace: nagp26
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: gce
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nagp26-app
                port:
                  number: 8080

