apiVersion: v1
kind: Secret
metadata:
  name: sql-credentials
stringData:
  sa-password: "YourStrong!Passw0rd"
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-conn
stringData:
  connectionString: "Server=nagp26-sql;Database=NAGP26_DB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;"
