apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-allow-api
spec:
  podSelector:
    matchLabels:
      app: nagp26-sql
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "nagp26-api.name" . }}
      ports:
        - protocol: TCP
          port: 1433
  policyTypes:
    - Ingress
