apiVersion: v1
kind: Secret
metadata:
  name: sql-credentials
type: Opaque
stringData:
  DB_USER: "{{ .Values.sql.appUser }}"
  DB_PASSWORD: "{{ .Values.sql.appPassword }}"
  SA_PASSWORD: "{{ .Values.sql.saPassword }}"
